---
version: "3.0"

services:
  ds_app:
    build:
      context: .
      args:
        REST_PORT : ${REST_PORT}
        # no_proxy:  artifacthub-tip.siriuscorp.com,artifactory-slc.siriuscorp.com
        DATASCIENCE_HOME: ${DATASCIENCE_HOME}
    environment:
      - MODE=dev
      - DATASCIENCE_HOME=${DATASCIENCE_HOME}
    volumes:
      - ${HOST_HOME_MODEL}:${DATASCIENCE_HOME}/models
      - ${HOST_HOME_DATAFILES}:${DATASCIENCE_HOME}/datafiles
      - ${HOST_HOME_LOGFILES}:${CONTAINER_HOME_LOGFILES}
      - ${HOST_HOME_CERT}:${CONTAINER_HOME_CERT}
    ports:
      - "${REST_PORT}:${REST_PORT}"
